# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_nhap = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_nhap.setObjectName("textEdit_nhap")
        self.verticalLayout.addWidget(self.textEdit_nhap)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_dichtu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dichtu.setObjectName("pushButton_dichtu")
        self.horizontalLayout.addWidget(self.pushButton_dichtu)
        self.pushButton__phatam = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__phatam.setObjectName("pushButton__phatam")
        self.horizontalLayout.addWidget(self.pushButton__phatam)
        self.pushButton_suatu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_suatu.setObjectName("pushButton_suatu")
        self.horizontalLayout.addWidget(self.pushButton_suatu)
        self.pushButton_themtu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_themtu.setObjectName("pushButton_themtu")
        self.horizontalLayout.addWidget(self.pushButton_themtu)
        self.pushButton_xoatu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_xoatu.setObjectName("pushButton_xoatu")
        self.horizontalLayout.addWidget(self.pushButton_xoatu)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit_xuat = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_xuat.setObjectName("textEdit_xuat")
        self.verticalLayout.addWidget(self.textEdit_xuat)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 21))
        # self.menubar.setObjectName("menubar")
        # self.menuedit = QtWidgets.QMenu(self.menubar)
        # self.menuedit.setObjectName("menuedit")
        # MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_quanly = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_quanly.sizePolicy().hasHeightForWidth())
        self.dockWidget_quanly.setSizePolicy(sizePolicy)
        self.dockWidget_quanly.setMinimumSize(QtCore.QSize(274, 559))
        self.dockWidget_quanly.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidget_quanly.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_quanly.setObjectName("dockWidget_quanly")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_tudatra = QtWidgets.QListWidget(self.dockWidgetContents_2)
        self.listWidget_tudatra.setMinimumSize(QtCore.QSize(256, 519))
        self.listWidget_tudatra.setObjectName("listWidget_tudatra")
        self.gridLayout.addWidget(self.listWidget_tudatra, 0, 0, 1, 1)
        self.dockWidget_quanly.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_quanly)
        self.actionthem_tu = QtWidgets.QAction(MainWindow)
        self.actionthem_tu.setObjectName("actionthem_tu")
        # self.menuedit.addSeparator()
        # self.menuedit.addAction(self.actionthem_tu)
        # self.menubar.addAction(self.menuedit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Từ điển"))
        self.pushButton_dichtu.setText(_translate("MainWindow", "Dịch từ"))
        self.pushButton__phatam.setText(_translate("MainWindow", "Phát âm"))
        self.pushButton_suatu.setText(_translate("MainWindow", "Sửa từ"))
        self.pushButton_themtu.setText(_translate("MainWindow", "Thêm từ"))
        self.pushButton_xoatu.setText(_translate("MainWindow", "Xóa từ"))
        # self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.actionthem_tu.setText(_translate("MainWindow", "them tu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
