# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'themtu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from themtu_ui import Ui_MainWindow
from PyQt5.QtWidgets import QMainWindow, QMessageBox
from pydb import Database
from PyQt5.QtGui import QIcon


class  ThemTu(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setWindowIcon(QIcon('./anh/icon/icon.png')) 
        self.show()
        self.database = Database("./database/data_word.db")
        self.run()
    def them_tu(self):
        # lay du lieu
        # truy van
        # if self.ui.textEdit_noidung.toPlainText()
        list_word = self.ui.textEdit_noidung.toPlainText().split("\n")
        e_word = list_word[0].split(":")[1].strip()
        e_type = list_word[1].split(":")[1].strip()
        e_mean = list_word[4].split(":")[1].strip()
        e_des = list_word[3].split(":")[1].strip()
        e_pronouce = list_word[2].split(":")[1].strip()

        ######### select test 
        query = f"SELECT * FROM word WHERE e_word like '{e_word}'"
        get_return = self.database.execute(query, "get data")
        if e_word != "":
            if len(get_return) != 0 :
                ret = QMessageBox.question(self, 'MessageBox', "co so du lieu da co tu ton tai, ban co muon ghi de tu nay trong co so du lieu", QMessageBox.Yes | QMessageBox.No)

                if ret == QMessageBox.Yes:
                    query = f"UPDATE word SET e_type = '{e_type}', e_mean = '{e_mean}', e_des = '{e_des}', e_pronouce = '{e_pronouce}' WHERE  e_word = '{e_word}' "
                    self.database.execute(query)
                    print('Button QMessageBox.Yes clicked.')


            elif e_word != "" and len(get_return) == 0:
                query =  f"INSERT INTO word (e_word, e_type, e_pronouce, e_des, e_mean) VALUES ('{e_word}', '{e_type}','{e_pronouce}', '{e_des}','{e_mean}')"
                self.database.execute(query)

                ret = QMessageBox.question(self, 'MessageBox', "them thanh cong", QMessageBox.Ok)

        else:
            QMessageBox.question(self, 'MessageBox', "bạn cần định nghia từ khi thêm từ", QMessageBox.Ok)
                
               
            # self.statusBar().showMessage("them thanh cong")
        # else:

        #     #thanh cong thi bao tusbar
        #     # ko thi hien thi form khac va xu ly tiep
        #     ret = QMessageBox.question(self, 'MessageBox', "co so du lieu da co tu ton tai, ban co muon ghi de tu nay trong co so du lieu", QMessageBox.Yes | QMessageBox.No)

        #     if ret == QMessageBox.Yes:
        #         query = f"UPDATE word SET e_word = '{e_word}', e_type = '{e_type}', e_mean = '{e_mean}', e_des = '{e_des}', e_pronouce = '{e_pronouce}' "
        #         self.database.execute(query)
        #         print('Button QMessageBox.Yes clicked.')



    def run(self):
        self.ui.pushButton_themtu.clicked.connect(self.them_tu) 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    themtu = ThemTu()
    sys.exit(app.exec_())
